### ISSUE TITLE
Review all tasks and make sure that appropriate 'when' clause is supplied

### ISSUE THREAD

**Issue by atc0005** [atc0005/ansible-role-lxd-testenv#10]
Specific "flags" I am thinking of:

```yaml
# Flag that controls whether Python, sudo and other packages are installed as
# part of preparing new containers for management by Ansible.
lxd_containers_bootstrap: true

# Create service account, groups, enable SSH at boot, etc
lxd_containers_configure: true
```
