### ISSUE TITLE
Allow creation of containers using LXD image fingerprint in place of alias values

### ISSUE THREAD

**Issue by atc0005** [atc0005/ansible-role-lxd-testenv#16]
I just learned two things:

- Ubuntu keeps older images around, presumably for testing purposes
- You can reference them via fingerprint values (e.g., `eca0e0a2d859`)
- The Ansible `lxd_container` module is supposed to be able to reference this id when creating containers

## Creating LXD container via fingerprint via `lxc` command

`$ lxc image list ubuntu: | head`
```ShellSession
+--------------------+--------------+--------+-------------------------------------------------+---------+----------+-------------------------------+
|       ALIAS        | FINGERPRINT  | PUBLIC |                   DESCRIPTION                   |  ARCH   |   SIZE   |          UPLOAD DATE          |
+--------------------+--------------+--------+-------------------------------------------------+---------+----------+-------------------------------+
| a (5 more)         | 2d53824fdf89 | yes    | ubuntu 17.10 amd64 (release) (20180706)         | x86_64  | 169.51MB | Jul 6, 2018 at 12:00am (UTC)  |
+--------------------+--------------+--------+-------------------------------------------------+---------+----------+-------------------------------+
| a/arm64 (2 more)   | b80c64d35ad4 | yes    | ubuntu 17.10 arm64 (release) (20180706)         | aarch64 | 153.62MB | Jul 6, 2018 at 12:00am (UTC)  |
+--------------------+--------------+--------+-------------------------------------------------+---------+----------+-------------------------------+
| a/armhf (2 more)   | c4e73fb2c574 | yes    | ubuntu 17.10 armhf (release) (20180706)         | armv7l  | 152.81MB | Jul 6, 2018 at 12:00am (UTC)  |
+--------------------+--------------+--------+-------------------------------------------------+---------+----------+-------------------------------+
| a/i386 (2 more)    | e5885665a63a | yes    | ubuntu 17.10 i386 (release) (20180706)          | i686    | 172.43MB | Jul 6, 2018 at 12:00am (UTC)  |
```

`$ lxc image list ubuntu: | grep 'ubuntu 14.04 LTS amd64' | grep 2015`

```ShellSession
|                    | 0afd3f6ac0d7 | yes    | ubuntu 14.04 LTS amd64 (release) (20151218)     | x86_64  | 118.24MB | Dec 18, 2015 at 12:00am (UTC) |
|                    | 222b43568480 | yes    | ubuntu 14.04 LTS amd64 (release) (20151008)     | x86_64  | 117.78MB | Oct 8, 2015 at 12:00am (UTC)  |
|                    | 2b82675b6fbc | yes    | ubuntu 14.04 LTS amd64 (release) (20151005)     | x86_64  | 118.13MB | Oct 5, 2015 at 12:00am (UTC)  |
|                    | 3d45357b9e6d | yes    | ubuntu 14.04 LTS amd64 (release) (20150901.1)   | x86_64  | 118.22MB | Sep 1, 2015 at 12:00am (UTC)  |
|                    | 566a2520b43c | yes    | ubuntu 14.04 LTS amd64 (release) (20150813)     | x86_64  | 117.76MB | Aug 13, 2015 at 12:00am (UTC) |
|                    | 5d8a4d1d803a | yes    | ubuntu 14.04 LTS amd64 (release) (20150805)     | x86_64  | 117.99MB | Aug 5, 2015 at 12:00am (UTC)  |
|                    | 609e1b057120 | yes    | ubuntu 14.04 LTS amd64 (release) (20151217)     | x86_64  | 118.66MB | Dec 17, 2015 at 12:00am (UTC) |
|                    | 642ea8083da5 | yes    | ubuntu 14.04 LTS amd64 (release) (20150908)     | x86_64  | 118.28MB | Sep 8, 2015 at 12:00am (UTC)  |
|                    | 95a60e042eb1 | yes    | ubuntu 14.04 LTS amd64 (release) (20151105)     | x86_64  | 117.99MB | Nov 5, 2015 at 12:00am (UTC)  |
|                    | 99810b551eec | yes    | ubuntu 14.04 LTS amd64 (release) (20150924)     | x86_64  | 117.75MB | Sep 24, 2015 at 12:00am (UTC) |
|                    | a1448d43bb7c | yes    | ubuntu 14.04 LTS amd64 (release) (20150930)     | x86_64  | 118.19MB | Sep 30, 2015 at 12:00am (UTC) |
|                    | af7ba4a09657 | yes    | ubuntu 14.04 LTS amd64 (release) (20150731)     | x86_64  | 118.01MB | Jul 31, 2015 at 12:00am (UTC) |
|                    | b739c004c56e | yes    | ubuntu 14.04 LTS amd64 (release) (20151019)     | x86_64  | 118.13MB | Oct 19, 2015 at 12:00am (UTC) |
|                    | c1af576b8546 | yes    | ubuntu 14.04 LTS amd64 (release) (20151015)     | x86_64  | 118.32MB | Oct 15, 2015 at 12:00am (UTC) |
|                    | c319ba2e6700 | yes    | ubuntu 14.04 LTS amd64 (release) (20150724)     | x86_64  | 117.93MB | Jul 24, 2015 at 12:00am (UTC) |
|                    | ca6cdc6545ea | yes    | ubuntu 14.04 LTS amd64 (release) (20150928)     | x86_64  | 118.12MB | Sep 28, 2015 at 12:00am (UTC) |
|                    | ca7aa08e0e09 | yes    | ubuntu 14.04 LTS amd64 (release) (20150810)     | x86_64  | 117.80MB | Aug 10, 2015 at 12:00am (UTC) |
|                    | e352c4855f5e | yes    | ubuntu 14.04 LTS amd64 (release) (20151007)     | x86_64  | 118.27MB | Oct 7, 2015 at 12:00am (UTC)  |
|                    | e9a8bdfab6dc | yes    | ubuntu 14.04 LTS amd64 (release) (20150814)     | x86_64  | 118.23MB | Aug 14, 2015 at 12:00am (UTC) |
|                    | eae5992c9681 | yes    | ubuntu 14.04 LTS amd64 (release) (20150727)     | x86_64  | 117.89MB | Jul 27, 2015 at 12:00am (UTC) |
|                    | eca0e0a2d859 | yes    | ubuntu 14.04 LTS amd64 (release) (20151117)     | x86_64  | 118.18MB | Nov 17, 2015 at 12:00am (UTC) |
```

`$ lxc launch ubuntu:eca0e0a2d859 ubuntu-14-eca0e0a2d859 `
```ShellSession
Creating ubuntu-14-eca0e0a2d859
Starting ubuntu-14-eca0e0a2d859
```

`$ lxc exec ubuntu-14-eca0e0a2d859 -- ls -l /`
```ShellSession
total 64
drwxr-xr-x   2 root   root    4096 Nov 17  2015 bin
drwxr-xr-x   3 root   root    4096 Nov 17  2015 boot
drwxr-xr-x   9 root   root     520 Feb 11 18:25 dev
drwxr-xr-x  88 root   root    4096 Feb 11 18:25 etc
drwxr-xr-x   3 root   root    4096 Feb 11 18:25 home
drwxr-xr-x  19 root   root    4096 Nov 17  2015 lib
drwxr-xr-x   2 root   root    4096 Nov 17  2015 lib64
drwx------   2 root   root    4096 Nov 17  2015 lost+found
drwxr-xr-x   2 root   root    4096 Nov 17  2015 media
drwxr-xr-x   2 root   root    4096 Apr 10  2014 mnt
drwxr-xr-x   2 root   root    4096 Nov 17  2015 opt
dr-xr-xr-x 306 nobody nogroup    0 Feb 11 18:25 proc
drwx------   3 root   root    4096 Feb 11 18:25 root
drwxr-xr-x  15 root   root     620 Feb 11 18:25 run
drwxr-xr-x   2 root   root    4096 Nov 17  2015 sbin
drwxr-xr-x   2 root   root    4096 Nov 17  2015 srv
dr-xr-xr-x  13 nobody nogroup    0 Feb 11 13:32 sys
drwxrwxrwt   2 root   root    4096 Feb 11 18:26 tmp
drwxr-xr-x  10 root   root    4096 Nov 17  2015 usr
drwxr-xr-x  12 root   root    4096 Nov 17  2015 var
```

## Creating container via `lxd_container` Ansible module

**EDIT**: Pulled from https://github.com/atc0005/ansible-role-lxd-testenv/issues/16#issuecomment-465818354:

```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: Create a started container
      lxd_container:
        name: mycontainer
        state: started
        source:
          type: image
          mode: pull
          server: https://cloud-images.ubuntu.com/releases
          protocol: simplestreams
          fingerprint: e9a8bdfab6dc
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
```

**Comment by atc0005** [comment]
I found some examples which employ a different protocol and image server to accomplish this:

- https://github.com/ansible/ansible-modules-extras/issues/2744
- https://github.com/ansible/ansible/issues/25489
- https://github.com/ansible/ansible/issues/18882

Working task:

```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: Create a started container
      lxd_container:
        name: mycontainer
        state: started
        source:
          type: image
          mode: pull
          server: https://cloud-images.ubuntu.com/releases
          protocol: simplestreams
          fingerprint: e9a8bdfab6dc
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
```

Changes from example playbook task given in the [module documentation](https://docs.ansible.com/ansible/2.7/modules/lxd_container_module.html) emphasized:

```yaml
          server: https://cloud-images.ubuntu.com/releases
          protocol: simplestreams
          fingerprint: e9a8bdfab6dc
```

**Comment by atc0005** [comment]
I came across a guide which also provides an example of using the changes noted in the last post which links out to a GitHub repo with working examples:

- https://blog.sourcecode.de/posts/2016/11/25/how-to-create-lxd-containers-with-ansible-2-2/
- https://github.com/struegamer/ansible-work

**Comment by atc0005** [comment]
I think I've got enough of an idea already how to make this happen, but the larger question of how to arrange user-provided settings needs further research.

If this were just a single value it would be one thing, but if a fingerprint is provided then the user will also have to override the protocol (lxd to simplestreams) and the image server used (https://images.linuxcontainers.org to https://cloud-images.ubuntu.com/releases).

An easier first approach is to look for a non-empty value for `lxd_containers_source_fingerprint` and if found, go ahead and automatically override other values:

- `lxd_containers_source_protocol`
- `lxd_containers_source_server`
- `lxd_containers_source_alias` (apply `default(omit)` or set as empty string)

I vaguely recall reading how Graylog was handling this via a configuration dictionary that the user was responsible for supplying. ALL user-provided values were provided through this dictionary.

I think I also recall reading how they were applying various assert calls to validate all provided values. I will probably review their approach before going further with this.

**Comment by atc0005** [comment]
> I vaguely recall reading how Graylog was handling this via a configuration dictionary that the user was responsible for supplying. ALL user-provided values were provided through this dictionary.

I think I remember reading the details here:

https://github.com/elastic/ansible-elasticsearch#basic-elasticsearch-configuration

> All Elasticsearch configuration parameters are supported. This is achieved using a configuration map parameter 'es_config' which is serialized into the elasticsearch.yml file.
> The use of a map ensures the Ansible playbook does not need to be updated to reflect new/deprecated/plugin configuration parameters.
> 
> In addition to the es_config map, several other parameters are supported for additional functions e.g. script installation. These can be found in the role's defaults/main.yml file.

...

> The following illustrates applying configuration parameters to an Elasticsearch instance.

```yaml
- name: Elasticsearch with custom configuration
  hosts: localhost
  roles:
    - role: elastic.elasticsearch
  vars:
    es_instance_name: "node1"
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_config:
      node.name: "node1"
      cluster.name: "custom-cluster"
      discovery.zen.ping.unicast.hosts: "localhost:9301"
      http.port: 9201
      transport.tcp.port: 9301
      node.data: false
      node.master: true
      bootstrap.memory_lock: true
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_heap_size: 1g
    es_api_port: 9201
```
