### ISSUE TITLE
Variable handling does not seem to honor established variable precedence

### ISSUE THREAD

**Issue by atc0005** [atc0005/ansible-role-lxd-testenv#32]
While working on #16, I believe I found that I'm applying variable precedence in a non-standard way. For example, in most locations throughout the playbook I'm attempting to first reference a host-specific value before falling back to a role default, which happens to share the same name as what would be used in the playbook.

Because of the explicit order, hostvar values are given greater weight than Play or Task vars set within the playbook. This is backwards from what the official docs state.

This is mainly an issue because the majority of the tasks in this role are run from localhost and delegated as needed to containers. Those tasks make explicit reference to hostvars.

Example task from this role:

```yaml
    - name: Create containers
      delegate_to: localhost
      lxd_container:
        name: "{{ item }}"
        state: started
        # Allow overriding proxy server per host or group, fallback to role
        # default of empty string if not set
        config:
          "environment.http_proxy": "{{ hostvars[item]['lxd_containers_proxy_server'] | default(lxd_containers_proxy_server) }}"
          "environment.https_proxy": "{{ hostvars[item]['lxd_containers_proxy_server'] | default(lxd_containers_proxy_server) }}"
          "environment.ftp_proxy": "{{ hostvars[item]['lxd_containers_proxy_server'] | default(lxd_containers_proxy_server) }}"
        source:
          type: image
          mode: pull
          server: "{{ hostvars[item]['lxd_containers_image_server'] | default(lxd_containers_image_server) }}"
          protocol: lxd
          alias: "{{ hostvars[item]['lxd_containers_image_source'] | default(lxd_containers_image_source) }}"
        # Attempt to use host or group specific profiles, fallback to standard set if not specified
        profiles: "{{ hostvars[item]['lxd_containers_profiles'] | default(lxd_containers_profiles) }}"
        wait_for_ipv4_addresses: true
        timeout: 600
      register: container_creation_results
      with_items:
        - "{{ groups['all'] }}"
```

For this line:

```yaml
          "environment.http_proxy": "{{ hostvars[item]['lxd_containers_proxy_server'] | default(lxd_containers_proxy_server) }}"

```

The hostvars entry is given precedence over the role variable (which is logical), but it also unintentionally lowers the priority of the same variable name if set within a playbook.

I'll need to go back and flip the logic on all such variable references and perform further testing. Until this is done, I'll need to pause work on #16 and related issues.

- Ref: https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
