### ISSUE TITLE
Using curl on http://127.0.0.1/ forwards request to proxy server

### ISSUE THREAD

**Issue by atc0005** [atc0005/ansible-role-lxd-testenv#38]
The current setup when deploying proxy server settings to `/etc/environment` in Ubuntu containers (perhaps CentOS, didn't test) results in the request for 127.0.0.1 being forwarded on to the configured proxy.

In our case we're using a Squid proxy server to speed up package installation, so when I configured the role to use that proxy server this was the response given:

```
<div id="titles">
<h1>ERROR</h1>
<h2>The requested URL could not be retrieved</h2>
</div>
<hr>

<div id="content">
<p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1/">http://127.0.0.1/</a></p>

<blockquote id="error">
<p><b>Connection to 127.0.0.1 failed.</b></p>
</blockquote>

<p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>

<p>The remote host or network may be down. Please try the request again.</p>
```

I vaguely recall that you can configure some local resources to not be proxied, but I don't remember if that's at the client level or if Squid should be handling this differently.

**Comment by atc0005** [comment]
https://askubuntu.com/questions/175172/how-do-i-configure-proxies-without-gui

> ```
> http_proxy="http://myproxy.server.com:8080/"
> https_proxy="http://myproxy.server.com:8080/"
> ftp_proxy="http://myproxy.server.com:8080/"
> no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
> HTTP_PROXY="http://myproxy.server.com:8080/"
> HTTPS_PROXY="http://myproxy.server.com:8080/"
> FTP_PROXY="http://myproxy.server.com:8080/"
> NO_PROXY="localhost,127.0.0.1,localaddress,.localdomain.com"
> ```

https://wiki.archlinux.org/index.php/Proxy_settings#Environment_variables

> Some programs, such as wget and (used by pacman) curl, use environment variables of the form "protocol_proxy" to determine the proxy for a given protocol (e.g. HTTP, FTP, ...).
> 
> Below is an example on how to set these variables in a shell:
> 
> ```
>  export http_proxy=http://10.203.0.1:5187/
>  export https_proxy=$http_proxy
>  export ftp_proxy=$http_proxy
>  export rsync_proxy=$http_proxy
>  export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
> ```
> 
> Some programs look for the all caps version of the environment variables.

**Comment by atc0005** [comment]
- https://serverfault.com/questions/571887/why-wget-doesnt-read-http-proxy-in-uppercase-format
- https://unix.stackexchange.com/questions/212894/whats-the-right-format-for-the-http-proxy-environment-variable-caps-or-no-ca

**Comment by atc0005** [comment]
While I fixed the modifications of the `/etc/environment` file in #39, I forgot about the settings applied directly to the container via the `config` parameter for the `lxd_container` module.

**Comment by atc0005** [comment]
Note: with the existing changes already applied per #39, connecting via SSH and attempting to run a curl command against localhost (e.g., with nginx installed with default index page) the connection bypasses the proxy as intended, but when connecting via `lxc exec`, the container-specific profile settings are applied which do not (yet) contain the `no_proxy` or `NO_PROXY` environment variable settings needed.

**Comment by atc0005** [comment]
I evidently was too optimistic. The "fixes" applied in #40 do not agree with the lxd_container module.

This direct command-line approach works:

`lxc config set ansible-ubuntu-1 environment.no_proxy "localhost,127.0.0.1,localaddress,.localdomain.com"`

but setting the same thing via Ansible does not seem to fly:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'environment.no_proxy'
fatal: [ansible-centos-5 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1551400877.91-247836149621951/AnsiballZ_lxd_container.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1551400877.91-247836149621951/AnsiballZ_lxd_container.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1551400877.91-247836149621951/AnsiballZ_lxd_container.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_lxd_container_payload_FsoXWj/__main__.py\", line 603, in <module>\n  File \"/tmp/ansible_lxd_container_payload_FsoXWj/__main__.py\", line 599, in main\n  File \"/tmp/ansible_lxd_container_payload_FsoXWj/__main__.py\", line 509, in run\n  File \"/tmp/ansible_lxd_container_payload_FsoXWj/__main__.py\", line 401, in _started\n  File \"/tmp/ansible_lxd_container_payload_FsoXWj/__main__.py\", line 471, in _needs_to_apply_container_configs\n  File \"/tmp/ansible_lxd_container_payload_FsoXWj/__main__.py\", line 461, in _needs_to_change_container_config\nKeyError: 'environment.no_proxy'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```

**Comment by atc0005** [comment]
Evidently the syntax was wrong?

This works:

```yaml
        config:
          environment.http_proxy: '{{ lxd_containers_proxy_server }}'
          environment.https_proxy: '{{ lxd_containers_proxy_server }}'
          environment.ftp_proxy: '{{ lxd_containers_proxy_server }}'
          environment.no_proxy: 'localhost,127.0.0.1,localaddress,.localdomain.com'
          environment.HTTP_PROXY: '{{ lxd_containers_proxy_server }}'
          environment.HTTPS_PROXY: '{{ lxd_containers_proxy_server }}'
          environment.FTP_PROXY: '{{ lxd_containers_proxy_server }}'
          environment.NO_PROXY: 'localhost,127.0.0.1,localaddress,.localdomain.com'
```

but this does not:

```yaml
        config:
          "environment.http_proxy": "{{ lxd_containers_proxy_server }}"
          "environment.https_proxy": "{{ lxd_containers_proxy_server }}"
          "environment.ftp_proxy": "{{ lxd_containers_proxy_server }}"
          "environment.no_proxy": "localhost,127.0.0.1,localaddress,.localdomain.com"
          "environment.HTTP_PROXY": "{{ lxd_containers_proxy_server }}"
          "environment.HTTPS_PROXY": "{{ lxd_containers_proxy_server }}"
          "environment.FTP_PROXY": "{{ lxd_containers_proxy_server }}"
          "environment.NO_PROXY": "localhost,127.0.0.1,localaddress,.localdomain.com"
```
