### ISSUE TITLE
id_ed25519 already exists. Overwrite (y/n)?

### ISSUE THREAD

**Issue by atc0005** [atc0005/ansible-role-lxd-testenv#43]
Error output snippet:

```ShellSession
TASK [atc0005.lxd-testenv : Generate key for test environment container use] **************************************************************************************************************************************
Friday 01 March 2019  18:04:54 -0600 (0:00:00.192)       0:00:00.857 ********** 
Friday 01 March 2019  18:04:54 -0600 (0:00:00.192)       0:00:00.856 ********** 
fatal: [ansible-centos-1 -> localhost]: FAILED! => {"changed": true, "cmd": ["ssh-keygen", "-q", "-t", "ed25519", "-f", "/home/redhat/.ssh/id_ed25519", "-C", "Key pair used for LXD container management", "-N", ""], "delta": "0:00:00.028323", "end": "2019-03-01 18:04:55.476415", "msg": "non-zero return code", "rc": 1, "start": "2019-03-01 18:04:55.448092", "stderr": "", "stderr_lines": [], "stdout": "/home/redhat/.ssh/id_ed25519 already exists.\nOverwrite (y/n)? ", "stdout_lines": ["/home/redhat/.ssh/id_ed25519 already exists.", "Overwrite (y/n)? "]}
changed: [ansible-ubuntu-1 -> localhost]
```

The SSH public key creation step attempts to run multiple times in parallel and succeeds once when processing the ansible-ubuntu-1 host entry, but fails when attempting to repeat the process in parallel for ansible-centos-1.

This is a case where I failed to apply the `run_once` parameter as I should have.

**Comment by atc0005** [comment]
Relevant task:

```yaml
    # https://serverfault.com/questions/910071/how-to-generate-host-ssh-keys-via-ansible
    - name: Generate key for test environment container use
      delegate_to: localhost
      # Allow to run for each host, trusting in 'creates' to prevent
      # overwriting of existing key. This allows for a unique key per
      # container.
      # run_once: true
      command : >
        ssh-keygen
        -q
        -t ed25519
        -f '{{ lxd_host_ssh_private_key_for_containers }}'
        -C 'Key pair used for LXD container management'
        -N ''
      args:
        creates: "{{ lxd_host_ssh_private_key_for_containers }}"
      register: keygen_results
```

Evidently I meant to allow it to run simultaneously, but failed to take into consideration the "first run" problem. This will need some additional thought. My first idea is to add a retry, but I don't know if on a retry the task will see the key and continue on or if it will stick with it's first filesystem eval and "not see" that the key now exists on another retry attempt.
